# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-02 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_piece_image_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='collage_placement',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
