# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-02 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_piece_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='created',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='piece',
            name='finish_date',
            field=models.DateField(),
        ),
    ]
