# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20160702_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='orientation',
            field=models.CharField(default='landscape', max_length=20),
            preserve_default=False,
        ),
    ]
