# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-03 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_piece_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='orientation',
            field=models.CharField(choices=[('L', 'Landscape'), ('P', 'Portrait'), ('O', 'Other')], default='L', max_length=20),
        ),
    ]
