# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20160703_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='medium',
            field=models.CharField(default='Oil on Canvas', max_length=100),
            preserve_default=False,
        ),
    ]
